platform :ios, '14.0'

project 'ApiDemo.xcodeproj',
  'ProbeDebug' => :debug,
  'Release' => :release

target 'ApiDemo' do
  pod 'MobileEasyUse',
      :path => '../../..',
      :configurations => ['ProbeDebug']

  script_phase(
    :name => '[MobileEasyUse] Embed Runtime',
    :script => %q{"${PODS_PODFILE_DIR_PATH}/../../../integration/ios/Scripts/embed-mobile-easy-use.sh" --configuration "ProbeDebug"},
    :input_files => [
      '${PODS_PODFILE_DIR_PATH}/../../../integration/ios/Scripts/embed-mobile-easy-use.sh',
      '${PODS_PODFILE_DIR_PATH}/../../../integration/ios/Binaries/${PLATFORM_NAME}/MobileEasyUse.dylib',
      '${PODS_PODFILE_DIR_PATH}/../../../integration/ios/Binaries/${PLATFORM_NAME}/MobileEasyUseRuntime.dylib',
      '${PODS_PODFILE_DIR_PATH}/../../../integration/ios/MobileEasyUseRuntime.config'
    ],
    :output_files => [
      '${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/MobileEasyUse.dylib',
      '${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/MobileEasyUseRuntime.dylib',
      '${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/MobileEasyUseRuntime.config'
    ],
    :execution_position => :after_compile
  )
end
